export const COLOURS = {
  white: "#ffffff",
  black: "#000000",
  green: "#00AC76",
  red: "#C04345",
  blue: "#0043F9",
  backgroundLight: "#F0F0F3",
  backgroundMedium: "#B9B9B9",
  backgroundDark: "#777777",
};

export const Items = [
  {
    id: 1,
    name: "Áo Ba Lỗ Gân Dáng Ngắn Cổ Henley",
    description: [
      "Chất liệu waffle dày dặn",
      "Thiết kế cổ thuyền, tay ngắn để đáp ứng nhu cầu của khách hàng",
      "Viền tròn giúp tạo kiểu sơ vin hay không sơ vin đều đẹp",
      "Chất liệu waffle và dáng rộng thoải mái giúp dễ dàng tạo nhiều kiểu khác nhau",
    ],
    material: "Thân: 60% Bông, 40% Polyeste/ Bo: 70% Bông, 30% Polyeste",
    price: "391.000",
    createAt: "2022-05-19",
    modifiedAt: "2022-05-19",
    size: {
      S: 10,
      M: 5,
      L: 7,
      XL: 4,
    },
    images: [
      require("../../assets/images/1.1.jpg"),
      require("../../assets/images/1.2.jpg"),
      require("../../assets/images/1.3.jpg"),
    ],
  },
  {
    id: 2,
    name: "Áo Thun AIRism Cotton Cổ Tròn Không Tay",
    description: [
      "Chiều dài tay áo được cải tiến để có kiểu dáng đẹp hơn",
      "Được làm bằng cotton Supima® cho kết cấu trang nhã và cảm giác mềm mại",
      "Có thể mặc riêng hoặc phối với các trang phục khác.",
      "Thiết kế được cải tiến với cổ chữ V sâu.",
      "Thiết kế cơ bản dễ dàng phối hợp với nhiều loại quần hoặc chân váy khác nhau",
    ],
    material: "Thân: 60% Bông, 40% Polyeste/ Bo: 70% Bông, 30% Polyeste",
    price: "391.000",
    createAt: "2022-05-19",
    modifiedAt: "2022-05-19",
    size: {
      S: 10,
      M: 5,
      L: 7,
      XL: 4,
    },
    images: [
      require("../../assets/images/2.1.jpg"),
      require("../../assets/images/2.2.jpg"),
      require("../../assets/images/2.3.jpg"),
    ],
  },
  {
    id: 3,
    name: "Áo Thun AIRism Cotton Cổ 3 Phân Ngắn Tay",
    description: [
      "Chất liệu AIRism cotton mềm mát.",
      "Thiết kế cổ giả.",
      "Thiết kế dáng boxy rộng rãi với hai tà bất đối xứng.",
      "Các đường xẻ bên và hai tà không đối xứng tạo thêm điểm nhấn phong cách.",
      "Hoàn hảo để kết hợp cùng với áo khoác và quần từ trong cùng bộ sưu tập.",
    ],
    material: "Thân: 60% Bông, 40% Polyeste/ Bo: 70% Bông, 30% Polyeste",
    price: "391.000",
    createAt: "2022-05-19",
    modifiedAt: "2022-05-19",
    size: {
      S: 10,
      M: 5,
      L: 7,
      XL: 4,
    },
    images: [
      require("../../assets/images/3.1.jpg"),
      require("../../assets/images/3.2.jpg"),
      require("../../assets/images/3.3.jpg"),
    ],
  },
  {
    id: 4,
    name: "Áo Thun Vải Supima Cotton Cổ V Ngắn Tay",
    description: [
      "Chất liệu AIRism cotton mềm mát.",
      "Thiết kế cổ giả.",
      "Thiết kế dáng boxy rộng rãi với hai tà bất đối xứng.",
      "Các đường xẻ bên và hai tà không đối xứng tạo thêm điểm nhấn phong cách.",
      "Hoàn hảo để kết hợp cùng với áo khoác và quần từ trong cùng bộ sưu tập.",
    ],
    material: "Thân: 60% Bông, 40% Polyeste/ Bo: 70% Bông, 30% Polyeste",
    price: "391.000",
    createAt: "2022-05-19",
    modifiedAt: "2022-05-19",
    size: {
      S: 10,
      M: 5,
      L: 7,
      XL: 4,
    },
    images: [
      require("../../assets/images/4.1.jpg"),
      require("../../assets/images/4.2.jpg"),
      require("../../assets/images/4.3.jpg"),
    ],
  },
  {
    id: 5,
    name: "Áo Thun Dáng Ngắn Cổ Vuông Ngắn Tay",
    description: [
      "Chất liệu AIRism cotton mềm mát.",
      "Thiết kế cổ giả.",
      "Thiết kế dáng boxy rộng rãi với hai tà bất đối xứng.",
      "Các đường xẻ bên và hai tà không đối xứng tạo thêm điểm nhấn phong cách.",
      "Hoàn hảo để kết hợp cùng với áo khoác và quần từ trong cùng bộ sưu tập.",
    ],
    material: "Thân: 60% Bông, 40% Polyeste/ Bo: 70% Bông, 30% Polyeste",
    price: "391.000",
    createAt: "2022-05-19",
    modifiedAt: "2022-05-19",
    size: {
      S: 10,
      M: 5,
      L: 7,
      XL: 4,
    },
    images: [
      require("../../assets/images/5.1.jpg"),
      require("../../assets/images/5.2.jpg"),
      require("../../assets/images/5.3.jpg"),
    ],
  },
  {
    id: 6,
    name: "Áo Thun Cổ Tròn Kẻ Sọc Dáng Rộng Tay Lửng",
    description: [
      "Chất liệu AIRism cotton mềm mát.",
      "Thiết kế cổ giả.",
      "Thiết kế dáng boxy rộng rãi với hai tà bất đối xứng.",
      "Các đường xẻ bên và hai tà không đối xứng tạo thêm điểm nhấn phong cách.",
      "Hoàn hảo để kết hợp cùng với áo khoác và quần từ trong cùng bộ sưu tập.",
    ],
    material: "Thân: 60% Bông, 40% Polyeste/ Bo: 70% Bông, 30% Polyeste",
    price: "391.000",
    createAt: "2022-05-19",
    modifiedAt: "2022-05-19",
    size: {
      S: 10,
      M: 5,
      L: 7,
      XL: 4,
    },
    images: [
      require("../../assets/images/6.1.jpg"),
      require("../../assets/images/6.2.jpg"),
      require("../../assets/images/6.3.jpg"),
    ],
  },
  {
    id: 7,
    name: "Áo Thun Cổ Tròn Kẻ Sọc Dáng Rộng Tay Lửng",
    description: [
      "Chất liệu AIRism cotton mềm mát.",
      "Thiết kế cổ giả.",
      "Thiết kế dáng boxy rộng rãi với hai tà bất đối xứng.",
      "Các đường xẻ bên và hai tà không đối xứng tạo thêm điểm nhấn phong cách.",
      "Hoàn hảo để kết hợp cùng với áo khoác và quần từ trong cùng bộ sưu tập.",
    ],
    material: "Thân: 60% Bông, 40% Polyeste/ Bo: 70% Bông, 30% Polyeste",
    price: "391.000",
    createAt: "2022-05-19",
    modifiedAt: "2022-05-19",
    size: {
      S: 10,
      M: 5,
      L: 7,
      XL: 4,
    },
    images: [
      require("../../assets/images/7.1.jpg"),
      require("../../assets/images/7.2.jpg"),
      require("../../assets/images/7.3.jpg"),
    ],
  },
  {
    id: 8,
    name: "Áo Thun Kẻ Sọc Ngắn Tay",
    description: [
      "Chất liệu AIRism cotton mềm mát.",
      "Thiết kế cổ giả.",
      "Thiết kế dáng boxy rộng rãi với hai tà bất đối xứng.",
      "Các đường xẻ bên và hai tà không đối xứng tạo thêm điểm nhấn phong cách.",
      "Hoàn hảo để kết hợp cùng với áo khoác và quần từ trong cùng bộ sưu tập.",
    ],
    material: "Thân: 60% Bông, 40% Polyeste/ Bo: 70% Bông, 30% Polyeste",
    price: "391.000",
    createAt: "2022-05-19",
    modifiedAt: "2022-05-19",
    size: {
      S: 10,
      M: 5,
      L: 7,
      XL: 4,
    },
    images: [
      require("../../assets/images/8.1.jpg"),
      require("../../assets/images/8.2.jpg"),
      require("../../assets/images/8.3.jpg"),
    ],
  },
  {
    id: 9,
    name: "Áo Thun Cổ Tròn Ngắn Tay Indigo",
    description: [
      "Chất liệu AIRism cotton mềm mát.",
      "Thiết kế cổ giả.",
      "Thiết kế dáng boxy rộng rãi với hai tà bất đối xứng.",
      "Các đường xẻ bên và hai tà không đối xứng tạo thêm điểm nhấn phong cách.",
      "Hoàn hảo để kết hợp cùng với áo khoác và quần từ trong cùng bộ sưu tập.",
    ],
    material: "Thân: 60% Bông, 40% Polyeste/ Bo: 70% Bông, 30% Polyeste",
    price: "391.000",
    createAt: "2022-05-19",
    modifiedAt: "2022-05-19",
    size: {
      S: 10,
      M: 5,
      L: 7,
      XL: 4,
    },
    images: [
      require("../../assets/images/9.1.jpg"),
      require("../../assets/images/9.2.jpg"),
      require("../../assets/images/9.3.jpg"),
    ],
  },
  {
    id: 10,
    name: "Áo Tank Top DRY Gân Nhiều Màu",
    description: [
      "Chất liệu AIRism cotton mềm mát.",
      "Thiết kế cổ giả.",
      "Thiết kế dáng boxy rộng rãi với hai tà bất đối xứng.",
      "Các đường xẻ bên và hai tà không đối xứng tạo thêm điểm nhấn phong cách.",
      "Hoàn hảo để kết hợp cùng với áo khoác và quần từ trong cùng bộ sưu tập.",
    ],
    material: "Thân: 60% Bông, 40% Polyeste/ Bo: 70% Bông, 30% Polyeste",
    price: "391.000",
    createAt: "2022-05-19",
    modifiedAt: "2022-05-19",
    size: {
      S: 10,
      M: 5,
      L: 7,
      XL: 4,
    },
    images: [
      require("../../assets/images/10.1.jpg"),
      require("../../assets/images/10.2.jpg"),
      require("../../assets/images/10.3.jpg"),
    ],
  },
  {
    id: 11,
    name: "Áo Thun Cotton Mềm Xếp Tầng Không Tayx",
    description: [
      "Chất liệu AIRism cotton mềm mát.",
      "Thiết kế cổ giả.",
      "Thiết kế dáng boxy rộng rãi với hai tà bất đối xứng.",
      "Các đường xẻ bên và hai tà không đối xứng tạo thêm điểm nhấn phong cách.",
      "Hoàn hảo để kết hợp cùng với áo khoác và quần từ trong cùng bộ sưu tập.",
    ],
    material: "Thân: 60% Bông, 40% Polyeste/ Bo: 70% Bông, 30% Polyeste",
    price: "391.000",
    createAt: "2022-05-19",
    modifiedAt: "2022-05-19",
    size: {
      S: 10,
      M: 5,
      L: 7,
      XL: 4,
    },
    images: [
      require("../../assets/images/11.1.jpg"),
      require("../../assets/images/11.2.jpg"),
      require("../../assets/images/11.3.jpg"),
    ],
  },
  {
    id: 12,
    name: "Áo Thun Kẻ Sọc Ngắn Tay",
    description: [
      "Chất liệu AIRism cotton mềm mát.",
      "Thiết kế cổ giả.",
      "Thiết kế dáng boxy rộng rãi với hai tà bất đối xứng.",
      "Các đường xẻ bên và hai tà không đối xứng tạo thêm điểm nhấn phong cách.",
      "Hoàn hảo để kết hợp cùng với áo khoác và quần từ trong cùng bộ sưu tập.",
    ],
    material: "Thân: 60% Bông, 40% Polyeste/ Bo: 70% Bông, 30% Polyeste",
    price: "391.000",
    createAt: "2022-05-19",
    modifiedAt: "2022-05-19",
    size: {
      S: 10,
      M: 5,
      L: 7,
      XL: 4,
    },
    images: [
      require("../../assets/images/12.1.jpg"),
      require("../../assets/images/12.2.jpg"),
      require("../../assets/images/12.3.jpg"),
    ],
  },
  {
    id: 13,
    name: "Monochrome Mickey UT Áo Thun Ngắn Tay",
    description: [
      "Chất liệu AIRism cotton mềm mát.",
      "Thiết kế cổ giả.",
      "Thiết kế dáng boxy rộng rãi với hai tà bất đối xứng.",
      "Các đường xẻ bên và hai tà không đối xứng tạo thêm điểm nhấn phong cách.",
      "Hoàn hảo để kết hợp cùng với áo khoác và quần từ trong cùng bộ sưu tập.",
    ],
    material: "Thân: 60% Bông, 40% Polyeste/ Bo: 70% Bông, 30% Polyeste",
    price: "391.000",
    createAt: "2022-05-19",
    modifiedAt: "2022-05-19",
    size: {
      S: 10,
      M: 5,
      L: 7,
      XL: 4,
    },
    images: [
      require("../../assets/images/13.1.jpg"),
      require("../../assets/images/13.2.jpg"),
      require("../../assets/images/13.3.jpg"),
    ],
  },
  {
    id: 14,
    name: "Áo Thun Ngắn Tay Cotton Mềm Diềm Xếp Nếp",
    description: [
      "Chất liệu AIRism cotton mềm mát.",
      "Thiết kế cổ giả.",
      "Thiết kế dáng boxy rộng rãi với hai tà bất đối xứng.",
      "Các đường xẻ bên và hai tà không đối xứng tạo thêm điểm nhấn phong cách.",
      "Hoàn hảo để kết hợp cùng với áo khoác và quần từ trong cùng bộ sưu tập.",
    ],
    material: "Thân: 60% Bông, 40% Polyeste/ Bo: 70% Bông, 30% Polyeste",
    price: "391.000",
    createAt: "2022-05-19",
    modifiedAt: "2022-05-19",
    size: {
      S: 10,
      M: 5,
      L: 7,
      XL: 4,
    },
    images: [
      require("../../assets/images/14.1.jpg"),
      require("../../assets/images/14.2.jpg"),
      require("../../assets/images/14.3.jpg"),
    ],
  },
];
